default: &default
  app_concurrency: 5
  sidekiq_concurrency: 5
  redis_url: "redis://127.0.0.1:6379/0"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  app_concurrency: 16
  sidekiq_concurrency: 25
